### ISSUE TITLE
Rename issue

### ISSUE THREAD

**Issue by Shamvuchandradas** [justdjango/django_project_boilerplate#10]
python3 manage.py rename djecommerce 
usage: manage.py rename [-h] [--version] [-v {0,1,2,3}] [--settings SETTINGS]
                        [--pythonpath PYTHONPATH] [--traceback] [--no-color]
                        [--force-color]
                        current [current ...] new [new ...]
manage.py rename: error: the following arguments are required: new

**Comment by bluemandsdev** [comment]
Run this instead:
> python manage.py rename demo "new project name"

**Comment by Shamvuchandradas** [comment]
thank a lot.
