### ISSUE TITLE
rename project doesn't work

### ISSUE THREAD

**Issue by sohailmerchant** [justdjango/django_project_boilerplate#3]
I just wanted watching the watch and immediately faced with an issue with renaming the project.  I did provide current name and the new name but receiving the following error:

FileNotFoundError: [Errno 2] No such file or directory: 'django_project_boilerplate/settings.py'

Any idea?

Thanks,

**Comment by rahul7011** [comment]
use this --> python manage.py rename demo your_project_name

**Comment by sohailmerchant** [comment]
Thanks I feel so stupid.  I thought the project name is 'django_project_boilerplate'.
